name: Test and Deploy Image

on:
  push:
    branches: [ main ]

jobs:

  lint-code:

    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Lint the python code
        uses: github/super-linter:slim-v4

  