name: Test and Deploy Image

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
      -uses: actions/checkout@v3
      -name: Lint the python code
       uses: github/super-linter:slim@v4

  