name: Test and Deploy Image

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Lint code base
    runs-on: ubuntu-latest

    steps: 

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Lint the python code
        uses: github/super-linter/slim@v4

  